[profile.default]
src = "contracts"
script = "scripts"
out = "out"
libs = ["lib"]
solc = "0.8.28"
remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "solady/=lib/solady/src/"
]
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.default.fmt]
line_length = 100
tab_width = 4
bracket_spacing = false

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
